package com.streamnz.model.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * User entity class
 * Represents the user table in the database
 */
@Data
@TableName("users")
@Schema(description = "User entity")
public class User {

    @TableId(type = IdType.INPUT)
    @Schema(description = "User ID (generated by Snowflake algorithm)")
    private Long id;

    @Schema(description = "Username")
    private String username;

    @Schema(description = "Password (encoded)")
    private String password;

    @Schema(description = "Email address")
    private String email;

    @Schema(description = "Full name")
    private String fullName;

    @Schema(description = "User role", example = "USER")
    private String role;

    @Schema(description = "Enabled status", example = "true")
    private Boolean enabled;

    @Schema(description = "Created time")
    private LocalDateTime createdAt;

    @Schema(description = "Updated time")
    private LocalDateTime updatedAt;
}
